repos:
  - repo: local
    hooks:
      - id: run-unittest
        name: Run unit tests with unittest
        entry: python -m unittest discover -s . -p 'unit_tests\tests_*.py'
        language: system
        types: [python]
        pass_filenames: false
